### ISSUE TITLE
[HA 2023.09.0] Deprecated forecast

### ISSUE THREAD

**Issue by WVoo** [toringer/home-assistant-met-next-6-hours-forecast#5]
After update HA to september patch. HomeAssistant reporting issue with integration:

> The met_next_6_hours_forecast integration is using deprecated forecast
> The integration met_next_6_hours_forecast is using the deprecated forecast attribute.
> 
> Will stop working in version 2024.3.0
> 
> Please report it to the custom integration author..

**Comment by LeonCB** [comment]
For more info:

https://www.home-assistant.io/blog/2023/09/06/release-20239/#weather-forecast-service

**Comment by toringer** [comment]
Fixed in v1.1.1
