### ISSUE TITLE
Deprecated constants 

### ISSUE THREAD

**Issue by LaurisGale** [toringer/home-assistant-met-next-6-hours-forecast#6]
3 Deprecated constants raise a warning in HA 2024.2:

- TEMP_CELSIUS was used from met_next_6_hours_forecast, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead.
- SPEED_METERS_PER_SECOND was used from met_next_6_hours_forecast, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfSpeed.METERS_PER_SECOND instead
- LENGTH_MILLIMETERS was used from met_next_6_hours_forecast, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfLength.MILLIMETERS instead

**Comment by toringer** [comment]
Thanks for letting me know 👍 Fixed in v1.1.2
